### PR TITLE
fix: second-level domain and port support misjudgement

### PR DESCRIPTION
**Pull request by XadillaX**
##### Checklist

- [x] `npm test` passes
- [x] tests and/or benchmarks are included
- [x] commit message follows commit guidelines

##### Affected core subsystem(s)

egg-cors

### CODE REVIEW

**Review by popomore — APPROVED** [review]

**Comment by popomore** [comment]
配置忽略端口

**Comment by popomore** [comment]
@dead-horse 有安全风险吗

**Comment by dead-horse** [comment]
最好是实现成不影响之前的配置方式吧，要么通过配置打开，要么用特殊的语法或者其他配置项。

**Review by atian25 — APPROVED** [review]

**Review by dead-horse — APPROVED** [review]

**Pull request merged**
